### PR TITLE
Implement min

### PR DESCRIPTION
**Pull request by huntc**
We have max, need min for phases also.

I've also changed Temperature to a precision of 2 decimal places based purely on that is the precision received from the nRF temperature peripheral.

### CODE REVIEW

**Comment by arnolddevos** [comment]
Could you also fix an old comment on line 283 impl FixedPoint<unit::Watt> which should say 1x scale.

**Comment by arnolddevos** [comment]
The min method looks good.  Why rescale Celsius to x100?  But I guess there are plenty of bits available.

**Review by arnolddevos — APPROVED** [review]

**Comment by huntc** [comment]
> Could you also fix an old comment on line 283 impl FixedPointunit::Watt which should say 1x scale.

Done

**Comment by huntc** [comment]
> The min method looks good. Why rescale Celsius to x100? But I guess there are plenty of bits available.

The *only* reason is that we have a precision of 2 when reading temperature from the nRF52840 sensor. Saves further conversions by upping the precision here.

**Pull request merged**
